<?php

//-------------------------------------------------------------------------------------------|
//  hook_ckeditor_plugin
//-------------------------------------------------------------------------------------------|


function singtwocols_ckeditor_plugin() {
  $module_path = drupal_get_path('module', 'singtwocols');
  return array(
    'singtwocols' => array(
      'name' => 'singtwocols',
      'desc' => 'Singular Two Columns insert',
      'path' => $module_path . '/static/',
      'buttons' => array(
        'singtwocols' => array(
          'icon' => 'icons/twocols.png',
          'label' => 'Sing Button',
        ),
      ),
    ),
  );
}